logger:
  level: info              # 日志级别(debug, info, warn, error)
  encoding: console        # 输出格式(console, json)
  outputPaths:             # 输出路径
    - stdout               # 标准输出
    - ./logs/client.log    # 文件输出
  errorOutputPaths:        # 错误输出路径
    - stderr               # 标准错误输出
    - ./logs/client-error.log     # 错误文件输出
  maxSize: 10              # 日志文件最大尺寸(MB)
  maxBackups: 5            # 日志文件最多保留个数
  maxAge: 30               # 日志文件最多保留天数
  compress: false          # 是否压缩

client:
  syncDir: '/home/lake/fsync-test-dir'        # 默认同步目录
  serverAddr: "localhost:8080"  # 服务器地址
  tokenDir: "~/.fsync"     # Token存储目录
  protocol: "https"         # 协议 (http 或 https)